import { StyleSheet } from "react-native";
import { Fonts } from "../constants/fonts.constants";

export const GlobalTextStyles = StyleSheet.create({
	h1Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:48,
		lineHeight:67,
		includeFontPadding:false,
	},
	h2Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:40,
		lineHeight:48,
		includeFontPadding:false,
	},
	h3Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:33,
		lineHeight:40,
		includeFontPadding:false,
	},
	h4Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:28,
		lineHeight:34,
		includeFontPadding:false,
	},
	h5Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:24,
		lineHeight:30,
		includeFontPadding:false,
	},
	title1Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:20,
		lineHeight:28,
		includeFontPadding:false,
	},
	title2Cormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:16,
		lineHeight:23,
		includeFontPadding:false,
	},
	bodyCormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:14,
		lineHeight:20,
		includeFontPadding:false,
	},
	captionCormorant:{
		fontFamily:Fonts.cormorantGaramond.bold700,
		fontSize:11,
		lineHeight:16,
		includeFontPadding:false,
	},
    h1Bold: {
		fontFamily: Fonts.dmSans.bold700,
		fontSize: 48,
		lineHeight: 67,
		includeFontPadding: false,
	},
	h1SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize: 48,
		includeFontPadding: false,
		lineHeight: 67,
	},
	h1Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize: 48,
		lineHeight: 67,
		includeFontPadding: false,
	},
	h1Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize: 48,
		lineHeight: 67,
		includeFontPadding: false,
	},
	h1Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize: 48,
		lineHeight: 67,
		includeFontPadding: false,
	},
	h2Bold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize: 40,
		lineHeight: 56,
		includeFontPadding: false,
	},
	h2SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize: 40,
		lineHeight: 56,
		includeFontPadding: false,
	},
	h2Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize: 40,
		lineHeight: 56,
		includeFontPadding: false,
	},
	h2Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize: 40,
		lineHeight: 56,
		includeFontPadding: false,
	},
	h2Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize: 40,
		lineHeight: 56,
		includeFontPadding: false,
	},
	h3Bold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize: 33,
		lineHeight: 47,
		includeFontPadding: false,
	},
	h3SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize: 33,
		lineHeight: 47,
		includeFontPadding: false,
	},
	h3Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize: 33,
		lineHeight: 47,
		includeFontPadding: false,
	},
	h3Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize: 33,
		lineHeight: 47,
		includeFontPadding: false,
	},
	h3Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize: 33,
		lineHeight: 47,
		includeFontPadding: false,
	},
	h4Bold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize: 28,
		lineHeight: 40,
		includeFontPadding: false,
	},
	h4SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize: 28,
		lineHeight: 40,
		includeFontPadding: false,
	},
	h4Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize: 28,
		lineHeight: 40,
		includeFontPadding: false,
	},
	h4Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize: 28,
		lineHeight: 40,
		includeFontPadding: false,
	},
	h4Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize: 28,
		lineHeight: 40,
		includeFontPadding: false,
	},
	h5Bold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize: 23,
		lineHeight: 33,
		includeFontPadding: false,
	},
	h5SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize: 23,
		lineHeight: 33,
		includeFontPadding: false,
	},
	h5Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize: 23,
		lineHeight: 33,
		includeFontPadding: false,
	},
	h5Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize: 23,
		lineHeight: 33,
		includeFontPadding: false,
	},
	h5Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize: 23,
		lineHeight: 33,
		includeFontPadding: false,
	},
	title1Bold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize:19,
		lineHeight: 27,
		includeFontPadding: false,
	},
	title1SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize:19,
		lineHeight: 27,
		includeFontPadding: false,
	},
	title1Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize:19,
		lineHeight: 27,
		includeFontPadding: false,
	},
	title1Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize:19,
		lineHeight: 27,
		includeFontPadding: false,
	},
	title1Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize:19,
		lineHeight: 27,
		includeFontPadding: false,
	},
	title2Bold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize:16,
		lineHeight: 23,
		includeFontPadding: false,
	},
	title2SemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize:16,
		lineHeight: 23,
		includeFontPadding: false,
	},
	title2Medium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize:16,
		lineHeight: 23,
		includeFontPadding: false,
	},
	title2Regular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize:16,
		lineHeight: 23,
		includeFontPadding: false,
	},
	title2Light:{
		fontFamily: Fonts.dmSans.light300,
		fontSize:16,
		lineHeight: 23,
		includeFontPadding: false,
	},
	bodyBold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize:14,
		lineHeight: 20,
		includeFontPadding: false,
	},
	bodySemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize:14,
		lineHeight: 20,
		includeFontPadding: false,
	},
	bodyMedium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize:14,
		lineHeight: 20,
		includeFontPadding: false,
	},
	bodyRegular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize:14,
		lineHeight: 20,
		includeFontPadding: false,
	},
	bodyLight:{
		fontFamily: Fonts.dmSans.light300,
		fontSize:14,
		lineHeight: 20,
		includeFontPadding: false,
	},
	captionBold:{
		fontFamily: Fonts.dmSans.bold700,
		fontSize:12,
		lineHeight: 17,
		includeFontPadding: false,
	},
	captionSemiBold:{
		fontFamily: Fonts.dmSans.semiBold600,
		fontSize:12,
		lineHeight: 17,
		includeFontPadding: false,
	},
	captionMedium:{
		fontFamily: Fonts.dmSans.medium500,
		fontSize:12,
		lineHeight: 17,
		includeFontPadding: false,
	},
	captionRegular:{
		fontFamily: Fonts.dmSans.regular400,
		fontSize:12,
		lineHeight: 17,
		includeFontPadding: false,
	},
	captionLight:{
		fontFamily: Fonts.dmSans.light300,
		fontSize:12,
		lineHeight: 17,
		includeFontPadding: false,
	},
});
